# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # 지정한 branch에서 push/pull_request 에 해당하는 command가 수행되면 이 workflow가 동작 합니다.
  # 여기서는 간단히 dev 브런치에서 push되면서 이 workflow가 실행 되도록 하겠습니다.
  push:
    branches: [main]

  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout release
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install package
        run: npm i

      - name: Build production bundle
        run: npm run build

      - name: directory
        run: |
          mkdir -p deploy/{server,client}
          mv client/build/* deploy/client
          mv dist/* deploy/server
          mv package.json deploy
          mv ValidateService .sh deploy
          mv appspec.yml deploy
          mv Dockerfile deploy

      - name: archive build
        run: |
          cd deploy
          tar cvfz ./deploy.tar.gz *
          ls

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy/deploy.tar.gz s3://chanoo-deploy/stock/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name chanoo-deploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name chanoo-deploy-stock
          --s3-location bucket=chanoo-deploy,bundleType=tgz,key=stock/deploy.tar.gz
